version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 50

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
